name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Electron App
        run: npm run build:electron 

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Windows-Release
          path: out/make/**/* 

      - name: Publish to GitHub Releases
        if: startsWith(github.ref, 'refs/tags/') # Only on tags
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: out/make/**/* # Upload all generated installers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
